server:
  port: 8080

spring:
  jpa:
    database: H2
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console

application:
  datasources:
    primary:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      connection-timeout: 20000
      connection-init-sql: SELECT 1
      maximum-pool-size: 5
      minimum-idle: 5
      idle-timeout: 10000
      max-lifetime: 20000
      auto-commit: false
      read-only: false

    secondary:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      connection-timeout: 20000
      connection-init-sql: SELECT 1
      minimum-idle: 6
      maximum-pool-size: 6
      idle-timeout: 10000
      max-lifetime: 20000
      auto-commit: false
      read-only: true

###
# connectionTimeout (default : 30000 (30 seconds))
# : ?????? pool? connection? ????? ???? ????? ?????.
#   ??? ??? ???? SQLException? ?????. (?? ??? ?? ?? ??? 250ms )
#
# maximunPoolSize (default : 10)
# : ?? ? ???? connection? ???? ?? ????? ?? ??? ??? ?????.
#   ??? ? ?? ???? ??? connectionTimeout ?? ?? ???? ??? ???? SQLException? ?????.
#
# minimumIdle (default : maximumPoolSize? ??)
# : connection pool?? ????? ?? ??? ??? ?????.
#   ??? ??? ???? ??? ? ?? ???? ??? ??? ???.
#
# idleTimeout (default : 600000 (10?))
# : connection pool?? ?? ??? ???? ?? ??? ?????.
#   ? ??? minimumIdle? maximumPoolSize?? ?? ???? ??? ? ????.
#   pool? ?? connection? minimumIdle? ??? ?? ??? ???? connection? ??? ?? ???? ?? idleTimeout ?? ?? ??? ??? ?????.
#
# maxLifeTime (default : 1800000 (30?))
# : connection? ?? ?? ??? ?????.
#   connection? maxLifeTime ??? ?, ???? connection? ?? ?????? ??? ???? ?????.
#   ??? ?? ???? ?? ?????.
#   maxLifeTime ???, db? wait_timeout ?? 2~3? ?? ??. ?? ???? ??? 5? ?? ?? ?? ??.
#
# readOnly (default : false)
# : pool?? ?? connection? ????? readOnly?? ???? ?????.
#   ??????? readOnly ??? ??? ???? ??? ? ????.
#
# connectionTestQuery (default : none)
# : ?????? ??? ??? ???????? ???? ?? pool?? connection? ???? ?? ???? ?????.
#   ????? JDBC4? ???? ?? ? ??? ???? ?? ?? ??????.
#