server:
  port: 8080

# 개발자가 설정하지 않으면 아래 정보로 기본값이 설정됨
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS: false
      INDENT_OUTPUT: true
      FAIL_ON_EMPTY_BEANS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
      READ_DATE_TIMESTAMPS_AS_NANOSECONDS: false
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: true
    mapper:
      USE_GETTERS_AS_SETTERS: false
  jpa:
    database: H2
    hibernate:
      ddl-auto: none
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        show-sql: true

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true # 콘솔 활성화 여부
      path: /h2-console # 콘솔 주소변경