# Student 전체 카운트
GET http://127.0.0.1:8080/student/totalCount

###

# Student 리스트
GET http://127.0.0.1:8080/student/list

###

# Student 조회
GET http://127.0.0.1:8080/student/1

###

# Student 등록
POST http://127.0.0.1:8080/student
Content-Type: application/json

{
  "name": "박석영",
  "grade": 2,
  "age": 18,
  "favorite_foods": [
    "치킨",
    "피자"
  ],
  "hobbies": [
    "축구",
    "프로그래밍"
  ],
  "parent": {
    "father_name": "ABC",
    "mother_name": "가나다"
  },
  "tag": {
    "title": "공부잘하는 학생"
  },
  "teachers": [
    "슨생님"
  ]
}

###

# Student 수정
PUT http://127.0.0.1:8080/student/1
Content-Type: application/json

{
  "name": "박석영",
  "grade": 2,
  "age": 19,
  "hobbies": [
    "농구",
    "프로그래밍"
  ]
}
###

# Student 삭제
DELETE http://127.0.0.1:8080/student/1

###