# Student 전체 카운트
GET http://127.0.0.1:8080/students/total-count

###

# Student 리스트
GET http://127.0.0.1:8080/students

###

# Student 조회
GET http://127.0.0.1:8080/students/1

###

# Student 등록
POST http://127.0.0.1:8080/students
Content-Type: application/json

{
  "name": "박석영",
  "grade": 2,
  "age": 18,
  "favorite_foods": [
    "치킨",
    "피자"
  ],
  "hobbies": [
    "축구",
    "프로그래밍"
  ],
  "parent": {
    "father_name": "ABC",
    "mother_name": "가나다"
  },
  "tag": {
    "title": "공부잘하는 학생",
    "order_num" : 1
  },
  "pets": [
    {
      "kind": "dog",
      "name": "쭈쭈",
      "age": 3
    }
  ],
  "classroom_names": [
    "햇님반"
  ],
  "teachers": [
    1
  ]
}

###

# Student 수정
PUT http://127.0.0.1:8080/students/1
Content-Type: application/json

{
  "name": "박석영2",
  "grade": 3,
  "age": 19,
  "favorite_foods": [
    "치킨",
    "피자",
    "국밥"
  ],
  "hobbies": [
    "축구",
    "프로그래밍",
    "팔찌공예"
  ],
  "parent": {
    "father_name": "ABCD",
    "mother_name": "가나다라"
  },
  "tag": {
    "seq": 1,
    "title": "공부잘하는 학생일까??"
  },
  "pets": [
    {
      "kind": "dog",
      "name": "쭈쭈",
      "age": 3
    }
  ],
  "classroom_names": [
    "햇님반일까?",
    "햇님반2"
  ],
  "teacher_sequences": [
    1
  ]
}
###

# Student 삭제
DELETE http://127.0.0.1:8080/students/1

###