server:
  port: 8080

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    # initialization-mode: always # 다른 데이터 베이스 초기화를 사용하기 위한 옵션 ( H2는 자동 실행 )
    # schema: schema.sql
    # data: data.sql

  h2:
    console:
      enabled: true # 콘솔 활성화 여부
      path: /h2-console # 콘솔 주소변경