server:
  port: 8080

spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none

application:
  datasources:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/master_db
      username: demo
      password: demo
      connection-timeout: 20000
      connection-init-sql: SELECT 1
      maximum-pool-size: 5
      minimum-idle: 5
      idle-timeout: 10000
      max-lifetime: 20000
      auto-commit: false
      read-only: false
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/slave_db
      username: demo
      password: demo
      connection-timeout: 20000
      connection-init-sql: SELECT 1
      minimum-idle: 6
      maximum-pool-size: 6
      idle-timeout: 10000
      max-lifetime: 20000
      auto-commit: false
      read-only: true

###
# connectionTimeout (default : 30000 (30 seconds))
# : \uD074\uB77C\uC774\uC5B8\uD2B8\uAC00 pool\uC5D0 connection\uC744 \uC694\uCCAD\uD558\uB294\uB370 \uAE30\uB2E4\uB9AC\uB294 \uCD5C\uB300\uC2DC\uAC04\uC744 \uC124\uC815\uD569\uB2C8\uB2E4.
#   \uC124\uC815\uD55C \uC2DC\uAC04\uC744 \uCD08\uACFC\uD558\uBA74 SQLException\uC774 \uBC1C\uC0DD\uD569\uB2C8\uB2E4. (\uD5C8\uC6A9 \uAC00\uB2A5\uD55C \uCD5C\uC18C \uC5F0\uACB0 \uC2DC\uAC04\uC740 250ms )
#
# maximunPoolSize (default : 10)
# : \uC720\uD734 \uBC0F \uC0AC\uC6A9\uC911\uC778 connection\uC744 \uD3EC\uD568\uD558\uC5EC \uD480\uC5D0 \uBCF4\uAD00\uAC00\uB2A5\uD55C \uCD5C\uB300 \uCEE4\uB125\uC158 \uAC1C\uC218\uB97C \uC124\uC815\uD569\uB2C8\uB2E4.
#   \uC0AC\uC6A9\uD560 \uC218 \uC788\uB294 \uCEE4\uB125\uC158\uC774 \uC5C6\uB2E4\uBA74 connectionTimeout \uC2DC\uAC04 \uB9CC\uD07C \uB300\uAE30\uD558\uACE0 \uC2DC\uAC04\uC744 \uCD08\uACFC\uD558\uBA74 SQLException\uC774 \uBC1C\uC0DD\uD569\uB2C8\uB2E4.
#
# minimumIdle (default : maximumPoolSize\uC640 \uB3D9\uC77C)
# : connection pool\uC5D0\uC11C \uC720\uC9C0\uAC00\uB2A5\uD55C \uCD5C\uC18C \uCEE4\uB125\uC158 \uAC1C\uC218\uB97C \uC124\uC815\uD569\uB2C8\uB2E4.
#   \uCD5C\uC801\uC758 \uC131\uB2A5\uACFC \uC751\uB2F5\uC131\uC744 \uC6D0\uD558\uBA74 \uC774 \uAC12\uC744 \uC124\uC815\uD558\uC9C0 \uC54A\uB294\uAC8C \uC88B\uB2E4\uACE0 \uD569\uB2C8\uB2E4.
#
# idleTimeout (default : 600000 (10\uBD84))
# : connection pool\uC5D0\uC11C \uC720\uD734 \uC0C1\uD0DC\uB85C \uC720\uC9C0\uC2DC\uD0AC \uCD5C\uB300 \uC2DC\uAC04\uC744 \uC124\uC815\uD569\uB2C8\uB2E4.
#   \uC774 \uC124\uC815\uC740 minimumIdle\uC774 maximumPoolSize\uBCF4\uB2E4 \uC791\uC740 \uACBD\uC6B0\uC5D0\uB9CC \uC0AC\uC6A9\uD560 \uC218 \uC788\uC2B5\uB2C8\uB2E4.
#   pool\uC5D0 \uC788\uB294 connection\uC774 minimumIdle\uC5D0 \uB3C4\uB2EC\uD560 \uACBD\uC6B0 \uC774\uD6C4\uC5D0 \uBC18\uD658\uB418\uB294 connection\uC5D0 \uB300\uD574\uC11C \uBC14\uB85C \uBC18\uD658\uD558\uC9C0 \uC54A\uACE0 idleTimeout \uB9CC\uD07C \uC720\uD734 \uC0C1\uD0DC\uB85C \uC788\uB2E4\uAC00 \uD3D0\uAE30\uB429\uB2C8\uB2E4.
#
# maxLifeTime (default : 1800000 (30\uBD84))
# : connection\uC758 \uCD5C\uB300 \uC720\uC9C0 \uC2DC\uAC04\uC744 \uC124\uC815\uD569\uB2C8\uB2E4.
#   connection\uC758 maxLifeTime \uC9C0\uB0AC\uC744 \uB54C, \uC0AC\uC6A9\uC911\uC778 connection\uC740 \uBC14\uB85C \uD3D0\uAE30\uB418\uC9C0\uC54A\uACE0 \uC791\uC5C5\uC774 \uC644\uB8CC\uB418\uBA74 \uD3D0\uAE30\uB429\uB2C8\uB2E4.
#   \uD558\uC9C0\uB9CC \uC720\uD734 \uCEE4\uB125\uC158\uC740 \uBC14\uB85C \uD3D0\uAE30\uB429\uB2C8\uB2E4.
#   maxLifeTime \uC124\uC815\uC740, db\uC758 wait_timeout \uBCF4\uB2E4 2~3\uCD08 \uC9E7\uAC8C \uC8FC\uC790. \uC880\uB354 \uC5EC\uC720\uC788\uAC8C \uC900\uB2E4\uBA74 5\uCD08 \uC815\uB3C4 \uC9E7\uAC8C \uC8FC\uBA74 \uB41C\uB2E4.
#
# readOnly (default : false)
# : pool\uC5D0\uC11C \uC5BB\uC740 connection\uC774 \uAE30\uBCF8\uC801\uC73C\uB85C readOnly\uC778\uC9C0 \uC9C0\uC815\uD558\uB294 \uC124\uC815\uC785\uB2C8\uB2E4.
#   \uB370\uC774\uD130\uBCA0\uC774\uC2A4\uAC00 readOnly \uC18D\uC131\uC744 \uC9C0\uC6D0\uD560 \uACBD\uC6B0\uC5D0\uB9CC \uC0AC\uC6A9\uD560 \uC218 \uC788\uC2B5\uB2C8\uB2E4.
#
# connectionTestQuery (default : none)
# : \uB370\uC774\uD130\uBCA0\uC774\uC2A4 \uC5F0\uACB0\uC774 \uC5EC\uC804\uD788 \uD65C\uC131\uD654\uB418\uC5B4\uC788\uB294\uC9C0 \uD655\uC778\uD558\uAE30 \uC704\uD574 pool\uC5D0\uC11C connection\uC744 \uC81C\uACF5\uD558\uAE30 \uC804\uC5D0 \uC2E4\uD589\uB418\uB294 \uCFFC\uB9AC\uC785\uB2C8\uB2E4.
#   \uB4DC\uB77C\uC774\uBC84\uAC00 JDBC4\uB97C \uC9C0\uC6D0\uD558\uB294 \uACBD\uC6B0 \uC774 \uC18D\uC131\uC744 \uC0AC\uC6A9\uD558\uC9C0 \uC54A\uB294 \uAC83\uC774 \uC88B\uB2E4\uACE0\uD569\uB2C8\uB2E4.
#