server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show-sql: true
    database: mysql

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo_db?serverTimezone=UTC
    username: demo
    password: demo