server:
  port: 8080

# 개발자가 설정하지 않으면 아래 정보로 기본값이 설정됨
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  h2:
    console:
      enabled: true # 콘솔 활성화 여부
      path: /h2-console # 콘솔 주소변경

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml